source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'debug'
gem 'sentry-ruby', path: '~/sentry/sdks/sentry-ruby/sentry-ruby'
gem "image_processing", "~> 1.0"
