redis: &redis
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  adapter: redis
  channel_prefix: sentry_rails_dev

test:
  adapter: test

production:
  adapter: redis
  channel_prefix: sentry_rails_sample_production
