example_job:
  cron: "* * * * *"
  class: "ExampleJob"
  args:
    - https://www.google.com

sidekiq_long_job:
  cron: "*/2 * * * *"
  class: "OuterLongAssName::InnerLongAssNameLongAssNameLongAssName::SidekiqJob"
  args:
    - https://www.google.com
