:scheduler:
  :schedule:
    example_job_scheduler:
      cron: '* * * * *'
      class: "ExampleJob"
      args:
        - https://www.google.com

    sidekiq_long_job_scheduler:
      every: "2 minutes"
      class: "OuterLongAssName::InnerLongAssNameLongAssNameLongAssName::SidekiqJob"
      args:
        - https://www.google.com
