:scheduler:
  :schedule:
    example_job_scheduler:
      cron: '*/1 * * * * Europe/Berlin' # Runs every 1 minute
      class: "ExampleJob"
      args:
        - https://www.google.com

    sidekiq_long_job_scheduler:
      every: "2 minutes"
      class: "OuterLongAssName::InnerLongAssNameLongAssNameLongAssName::SidekiqJob"
      args:
        - https://www.google.com
